[project]
name = "fucto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.0",
    "httpx==0.27.0",
    "pydantic==2.10.1",
    "tiktoken==0.7.0",
    "uvicorn==0.32.0",
    "websockets==14.1",
]
